"""add_send_report_on_engagement

Revision ID: 00e8d4134dbe
Revises: 812b1f67015a
Create Date: 2024-09-19 16:41:49.478981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e8d4134dbe'
down_revision = '812b1f67015a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement', sa.Column('send_report', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagement', 'send_report')
    # ### end Alembic commands ###
