"""add_description_to_report_setting

Revision ID: 538dd25f2a13
Revises: c8f3a1d92e47
Create Date: 2026-07-29 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '538dd25f2a13'
down_revision = 'c8f3a1d92e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_setting', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_setting', 'description')
    # ### end Alembic commands ###
