"""alter title length to max 200 characters

Revision ID: 9a93fda677eb
Revises: 25e6609cb4db
Create Date: 2024-05-24 14:41:49.995265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a93fda677eb'
down_revision = '25e6609cb4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('widget_documents', 'title',
               existing_type=sa.String(length=50),
               type_=sa.String(length=200))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('widget_documents', 'title',
               existing_type=sa.String(length=200),
               type_=sa.String(length=50))
    # ### end Alembic commands ###
