"""add timezone to event

Revision ID: c5ee420f661a
Revises: a72e849d93ad
Create Date: 2025-10-14 12:01:15.322303

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c5ee420f661a'
down_revision = 'a72e849d93ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_item', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.execute(sa.text("UPDATE event_item SET timezone = 'Canada/Pacific'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_item', 'timezone')
    # ### end Alembic commands ###
