name: MET CRON JOB CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "met-cron/**"
      - "met-api/**"

defaults:
  run:
    shell: bash
    working-directory: ./met-cron

jobs:
  setup-job:
    runs-on: ubuntu-22.04

    if: github.repository == 'bcgov/epic-engage'

    steps:
      - uses: actions/checkout@v2
      - run: "true"

  linting:
    needs: setup-job
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make setup
      - name: Lint with pylint
        id: pylint
        run: |
          make pylint
      - name: Lint with flake8
        id: flake8
        run: |
          make flake8


  build-check:
    needs: setup-job
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: build to check strictness
        id: build
        run: |
          make build-nc
